#! /bin/bash
# $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/grow-knoppix/Repository/grow-knoppix/alpha/grow-knoppix,v 1.26 2005/04/15 08:54:36 paradocs Exp $
# Checkout tag $Name:  $
###########AUTHOR'S LOG############
# $Log: grow-knoppix,v $
# Revision 1.26  2005/04/15 08:54:36  paradocs
# Further editing of menues
#
# Revision 1.25  2005/04/14 10:24:50  paradocs
# More editing of the menues to make it clearer.
#
# Revision 1.24  2005/04/14 07:43:25  paradocs
# Editing the help menues
#
# Revision 1.23  2005/04/14 06:42:02  paradocs
# Add headders for CVS    Reverted to version released on the web site
#
############END OF LOG#############
# Set the next line for your default DVD device, likely /dev/cdrom1 
DVD_BURNER="cdrom1"
BURN_SPEED="0"
# Default path to the directory KNOPPIX where file KNOPPIX is found
KNOPPIX_PATH="/mnt/cdrom"
PUBLISHER="PUBLISHED_BY_____________VERSION______________" 
XDIALOG_HIGH_DIALOG_COMPAT=1
export XDIALOG_HIGH_DIALOG_COMPAT
#XDIALOG_INFOBOX_TIMEOUT=1000000
#export XDIALOG_INFOBOX_TIMEOUT

echo -n "LANGUAGE=\"" > /var/tmp/LANGUAGE_CHOICE

Xdialog --title "GROW_KNOPPIX " --no-tags --radiolist "\n\n\
Publish your content in the root of a new KNOPPIX based live boot DVD.\n\
Change the boot file, background image, index.html, and desktop.\n\n\
Kopiere dein Inhalt in die root einer neuen Knoppix basierten live DVD.\n\
Ändere die Datei boot, das Hintergrundbild, die index.html\n\
und den Desktop.\n\n\
            OK     I have read             Cancel   Please read the help\n\
            the copyright and help.        and the GNU copyright.\n\n\
            
            OK. Ich habe die Bestimmungen  Cancel   Bitte lese die Hilfe\n\
            und Hilfe gelesen.             und das GNU copyright.\n\
" 35 85 10 "en" "English" "on" "de" "Deutsch nicht jetzt" "off" \
2>> /var/tmp/LANGUAGE_CHOICE
EXIT_CODE=$?

echo -n "\"" >> /var/tmp/LANGUAGE_CHOICE  #End quote for variable in file
. /var/tmp/LANGUAGE_CHOICE                #Source: run the file, set variable
LANGUAGE=${LANGUAGE%?}                    #Trim off unwanted tail
####  rm /var/tmp/LANGUAGE_CHOICE

if [ $EXIT_CODE -ne 0 ] ; then \
Xdialog --title "GROW_KNOPPIX " --msg "\
  Copyright (C) 2004   David M. Tan Creti <paradocs@berlios.de>\n\
                       Dyslexia Project\n\
                       Crawford County Memorial Hospital\n\
                       2020 1st Ave. South, Denison, Iowa 51442\n\n\
This program is free software; you can redistribute it and/or\n\
modify it under the terms of the GNU General Public License\n\
as published by the Free Software Foundation; either version 2\n\
of the License, or (at your option) any later version.\n\n\
This program is distributed in the hope that it will be useful,\n\
but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\n\
See the GNU General Public License for more details.\n\
You should have received a copy of the GNU General Public License\n\
along with this program; if not, write to the\n\
Free Software Foundation, Inc., 59 Temple Place - Suite 330,\n\
Boston, MA  02111-1307, USA.\n\n\
                             THANKS TO:\n  
kano.de and the IRC community of free.node.net #kanotix #knoppix\n\
This is experimental software -- use it at you own risk.\n
        Your reports and contributions will be appreciated.\n\n\
                         Hit OK for more HELP\
" 38 85


Xdialog --title "GROW_KNOPPIX " --msg "\
VERSIONS: The goal it to update to work with future KNOPPIX, KANOTIX\n\
          versions.  Remaking a DVD with the latest version is easy.\n\
SKILL:    This guide is designed to require only basic computer skills.\n\
ARCHIVE:  Archivists worry that electronic materials will quickly\n\
          become unreadable.  By keeping an operating system with the\n\
          content, KNOPPIX can be a standard for extending the live\n\
          of electronic content.\n\
SYSTEM:   The system required is a boot-able CD/DVD reader, DVD writer,\n\
          and a recomended 512MB memory.  No hard drive in required\n\
          but one is needed for copying large content to the DVD.\n\
SPEED:    Since data must be read in fast enought to supply the burner\n\
          sufficently fast drives, processor, and memory is needed.\n\
CONTENT:  Content may be place on the root of the DVD, copied into\n\
          /home/knoppix/  directory and as of 3.8.1 UNIONFS allows\n\
          adding new programs and configuration files to liunx root.\n\
FILES:    You must have no directories or files with the same name to\n\
          be combined.  The container directory/s is/are not created,\n\
          only the contents are combined in the root of the new DVD.\n\
BOOT:     Changing boot parameters in ~/GROW_KNOPPIX/KNOPPIX/boot.img\n\
          or in ~/GROW_KNOPPIX/ROOT/boot/isolinux/isolinux.cfg\n\
          can allow cheat codes for intervention free booting.\n\
INDEX:    Modify index.html in /home/knoppix/GROW_KNOPPIX/ROOT to show\n\
          your content.  Please make the original index.html pages\n\
          available to give proper credit.  Links and menus may be made.\n\
DESKTOP:  Desktop settings may be saved. K -> KNOPPIX -> Configure\n\
          -> save KNOPPIX conf.  Files knoppix.sh and configs.tbz may\n\
          be placed in /home/knoppix/GROW_KNOPPIX/ \n\
SPECIAL:  Customizing scripts can be run from knoppix.sh to make menus\n\
          and changes home and configuration files.\n\
                         Hit OK for more HELP\
" 40 85

Xdialog --title "GROW_KNOPPIX " --msg "\
    Steps to create a DVD:\n\
1)  Boot from the KNOPPIX or KANOTIX CD. Get grow-knoppix and run it.\n\
2)  Select the KNOPPIX or KANOTIX type of boot version.\n\
3)  Set the path to point to the KNOPPIX/KNOPPIX folder on your CD.\n\
4)  Creates at home GROW_KNOPPIX with subdirectories KNOPPIX and ROOT\n\
    Copys boot.img  into  KNOPPIX -or- boot folder into ROOT.\n\
    Copys /mnt/cdrom/index.html        into your ROOT    subdirectory.\n\
5)  Pick to make an .ios file to burn later or burn directly to a DVD.\n\
                             Hit OK to EXIT\
" 40 85

exit
fi

#########
echo -n "BOOT_VERSION=\"" > /var/tmp/BOOT_VERSION

Xdialog --title "GROW_KNOPPIX " --no-tags --radiolist "\n\n\
You must have a supported KNOPPIX or KANOTIX CD in you CD drive.\n\n\
1)  Select the boot method for your version of knoppix or kanotix.\n\
2)  Click on OK to setup at home:\n\
       GROW_KNOPPIX with subdirectories KNOPPIX and ROOT\n\
       Copy boot.img  into  KNOPPIX -or- boot folder into ROOT.\n\
       Copy /mnt/cdrom/index.html        into your ROOT    subdirectory.\n\n\
If these files already exist, clicking OK will not change them.\n\n\
" 35 85 10 \
"boot.img" "TYPE=/KNOPPIX/boot.img  KANOTIX BH5     KNOPPIX 3.3" "off" \
"isolinux.bin" "TYPE=/boot/isolinux/isolinux.bin  KNOPPIX 3.4    3.8.1" "off" \
"stage1_5" "TYPE=/boot/grub/stage2 KANOTIX BH6    2005-2" "on" 2>> /var/tmp/BOOT_VERSION
EXIT_CODE=$?

echo -n "\"" >> /var/tmp/BOOT_VERSION  #End quote for variable in file
. /var/tmp/BOOT_VERSION                #Source: run the file, set variable
BOOT_VERSION=${BOOT_VERSION%?} 

if [ $EXIT_CODE -ne 0 ] ; then exit; fi

########


Xdialog --title "GROW_KNOPPIX " --inputbox "\
Make sure the entry below points to the bootable CD to be copied.\n\
for example:        /mnt/cdrom   or   /mnt/cdrom1\n\n\n\
                            OPTIONS:\n\
BOOT     The boot files have been copied from the CD.  You may edit\n\
boot.img,   /boot/isolinux/isoliunx.cfg   or   /grub/stage2.\n\
The DVD can boot with special cheat codes with no intervention.\n\n\
INDEX    The file index.html has been copied from the boot CD DVD to\n\
the subdirectory ROOT.  You may edit index.html to describe you content.\n\
Please make the original index.html information available and give\n\
credit to the the original KNOPPIX disk.\n\n\
CONTENT  You may add files and directroies to:\n\
         GROW_KNOPPIX/ROOT/HOME to be copied to you home directory.\n\
         GROW_KNOPPIX/ROOT to be copied to the ROOT of you DVD\n\
         (Links to more contents and program will be added later.)\n\n\n\
      OK     I am happy with        Cancel\n\
      the content in                You may hit cancel and add\n\
      ~/GROW_KNOPPIX.               content and edit files in\n\
      Hit OK to specify your        ~/GROW_KNOPPIX. Then run this\n\
      method for burning a DVD.     again and pick  OK  next time.\n\
"   35 85 $KNOPPIX_PATH  2>> /var/tmp/KNOPPIX_PATH
EXIT_CODE=$?
. /var/tmp/KNOPPIX_PATH
rm /var/tmp/KNOPPIX_PATH

# make directories and copy files if not done manually or previously
mkdir /home/knoppix/GROW_KNOPPIX
mkdir /home/knoppix/GROW_KNOPPIX/KNOPPIX
mkdir /home/knoppix/GROW_KNOPPIX/ROOT
mkdir /home/knoppix/GROW_KNOPPIX/ROOT/HOME
####need to make   cdrom a varable $KNOPPIX_PATH
cp -u /mnt/cdrom/KNOPPIX/boot.img /home/knoppix/GROW_KNOPPIX/KNOPPIX/boot.img
cp -uRf /mnt/cdrom/boot /home/knoppix/GROW_KNOPPIX/ROOT/
cp -u /mnt/cdrom/index.html /home/knoppix/GROW_KNOPPIX/ROOT/index.html
chmod -R 777 /home/knoppix/GROW_KNOPPIX/ROOT
rm -f /home/knoppix/GROW_KNOPPIX/ROOT/boot/isolinux/boot.cat
rm -f /home/knoppix/GROW_KNOPPIX/ROOT/boot/grub/boot.cat
mkdir /var/tmp/GK_KNOPPIX
mkdir /var/tmp/GK_KNOPPIX/KNOPPIX
if [ $EXIT_CODE -ne 0 ] ; then \
exit
fi

#set a variable with the DVD write device
echo -n "GK_DVD_DEV=\"" > /var/tmp/GK_DVD_DEV

Xdialog --title "GROW_KNOPPIX " --2inputsbox "\
BURN DVD:  Make sure your DVD burner device is set below.\n\
For example:  /dev/cdrom  /dev/cdrom1  /dev/cdrom2 .\n\
For help you can see your devices by entering: cat /etc/fstab.\n\
Leave the Burn Speed set to zero to avoid getting the error message:\n\
unable to change burn speed\n\n\
                            -or-\n\n\
MAKE IOS:  Enter     iso   in the first line.\n\
Enter a path to a directory and name you ios in the second line.\n\
For example:  iso\n\
              /mnt/hda1/knoppix_clone_july04.iso\n\n\n\
                          to proceed hit \n\n\n\n\n\n\
                 OK               or            Cancel\
" 35 85 "Burn Speed (keep 0 for default) ----or enter---- iso " $BURN_SPEED "Burner: cdrom cdrom1 cdrom2 ----or enter---- /path/name.ios" \
$DVD_BURNER 2>> /var/tmp/GK_DVD_DEV
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ] ; then \
exit
fi

echo -n "\"" >> /var/tmp/GK_DVD_DEV        #End quote for variable in file
. /var/tmp/GK_DVD_DEV      #Source: run the file, set variable
GK_DVD_DEV=${GK_DVD_DEV%?}    #Glob strip of one character form the end
DVD_DEV=/dev/${GK_DVD_DEV#*/}
BURN_SPEED=${GK_DVD_DEV%/*}
rm /var/tmp/DVD_DEV     #Clean up

## set the default paths and add up to three more
##echo -n "DVD_ROOT=\"/var/tmp/BindCD/ /home/knoppix/GROW_KNOPPIX/ROOT/ \
##/home/knoppix/GROW_KNOPPIX/KNOPPIX/ /var/tmp/GK_KNOPPIX/ " > /var/tmp/DVD_ROOT
####tried to put knoppix.sh and configs.tbz in /KNOPPIX but failed
####I may need a second bind to do this.

echo -n "DVD_ROOT=\"/var/tmp/BindCD/ /home/knoppix/GROW_KNOPPIX/ROOT/ \
/home/knoppix/GROW_KNOPPIX/KNOPPIX/ /var/tmp/GK_KNOPPIX/ " > /var/tmp/DVD_ROOT

Xdialog --title "GROW_KNOPPIX " --3inputsbox "\
Content may come from up to 3 additional directories.\n\n\
The first directory created previously should \
include the file:   index.html\n\n\
Note:  The directory ROOT is not created on the DVD -- \n\
only it's contents is added together with others to the DVD root.\n\n\
Because of this, do not use files or directories of the same name.\n\n\
Include the final slash: for example   /mnt/hda1/ROOT/\n\n\
Enter paths for 2, 3, and 4 or leave blank if not needed.\n\n\
          Click  OK  to Continue.         Click  Cancel to EXIT\
" 35 85 "1.\n/home/knoppix/GROW_KNOPPIX/ROOT/ \n2." \
"" "3." "" "4." "" 2>> /var/tmp/DVD_ROOT
EXIT_CODE=$?

#########  echo -n "\"" >> /var/tmp/DVD_ROOT
## change    ///   to    / / 
## match anchored at end:   / and any number of (space or /)
##     and replace with a /" 
## then elimanate all space and / at the end except the last /
sed -e 's/\/\/\//\/ \//'g -e 's/\/[ /]*$/\/"/' \
/var/tmp/DVD_ROOT > /var/tmp/DVD_ROOT_PATHS

. /var/tmp/DVD_ROOT_PATHS  #source   set the variable DVD_ROOT
rm /var/tmp/DVD_ROOT
rm /var/tmp/DVD_ROOT_PATHS
 
if [ $EXIT_CODE -ne 0 ] ; then exit
fi

Xdialog --title "GROW_KNOPPIX " --no-tags --radiolist "\n\
You may now save your desktop configuration if you wish.\n\
If you do this, on boot your desktop changes with be restored.\n\n\
This will place configs.tbz and knoppix.sh on the root of your new DVD.\n\
Limitation:    Once you have a DVD with these configuration files you\n\
may not change them on future DVDs made with this DVD and grow-knoppix.\n\
You may start with a fresh KNOPPIX CD.\n\n\
configs.tbz and knoppix.sh are created at /var/temp/GK_KNOPPIX/KNOPPIX/\n\
Advanced users my edit them before thery are bruned to the DVD root.\n\n\
            OK     I have checked:             Cancel   Exit now.\n\
            YES for a new configs.tbz          You may make the  \n\
            and knoppix.sh to be added.        desired desktop changes\n\
                         or                              and\n\
            NO  for not changing or not        return later.\n\
            adding these files.\n\
" 35 85 10 "SAVE_CONFIG=0" "NO, do not make new configuration files" "on" "SAVE_CONFIG=1" "YES make new configuration files." "off" \
2> /var/tmp/GK_DESKTOP
EXIT_CODE=$?

. /var/tmp/GK_DESKTOP
rm /var/tmp/GK_DESKTOP

if [ $EXIT_CODE -ne 0 ] ; then \
exit
fi

if [ $SAVE_CONFIG -eq 1 ] ; then \
cp /usr/sbin/saveconfig /var/tmp/GK_SAVE1; \
sudo chmod a+x /var/tmp/GK_SAVE1; \

awk '!/^FLOPPYDIR=/ {print ;} /^FLOPPYDIR=/ {print $1" "$2" /var/tmp/GK_KNOPPIX/KNOPPIX " $4" "$5" "$6" "$7}' /var/tmp/GK_SAVE1 > /var/tmp/GK_SAVE2

awk '/^umountfloppy(){\nmount | grep -q \"\$FLOPPYDIR/ {print "exit" ;} !/^umountfloppy(){\nmount | grep -q \"\$FLOPPYDIR/  {print}' /var/tmp/GK_SAVE2 > /var/tmp/GK_SAVE1
    
awk '/^PARTITIONS=/ {print "PARTITIONS=\"/var/tmp/GK_KNOPPIX/KNOPPIX [/var/tmp/GK_KNOPPIX/KNOPPIX] on\"";} !/^PARTITIONS=/ {print}' /var/tmp/GK_SAVE1 > /var/tmp/GK_SAVE2

awk '/^mount/ {print "#"} !/^mount/ {print}' /var/tmp/GK_SAVE2 > /var/tmp/GK_SAVE1

#############################
exec /var/tmp/GK_SAVE1 &

Xdialog --title "GROW_KNOPPIX " --msg "\
WAIT  !!!\n\nClick   OK\n\
only after finishing configuration archive dialog has give the success \
message. The final message does not apply to grow-knoppix. \
The files will be placed the DVD root and will be detected at boot.\n\
" 30 20
rm GK_SAVE1
rm GK_SAVE2


Xdialog --title "GROW_KNOPPIX " --no-tags --radiolist "\n\n\
In addition to configuration files, you may have some files  placed in\n\
/home/knoppix/GROW_KNOPPIX/ROOT/HOME\n\
These will appear in the /home/knoppix directory after each boot.\n\n\
Caution: This recopies the same files at each boot and may interfear with\n\
the persistent home method of restoring files to /home/knoppix.\n\
For most purposes use the persistent home method.\n\n\
            OK     I have checked:             Cancel   Exit now.\n\n\
            YES so that my files will          You may make the  \n\
            be copied to HOME on boot.         desired desktop changes\n\n\
                         or                              and\n\n\
            NO   I do not want additional      return later.\n\
            files copied into HOME.\n\
" 35 85 10 "GK_HOME=0" "NO, do not copy additionwal files to HOME on boot." "on" "GK_HOME=1" "YES copy file to /home/knoppix on boot." "off" \
2> /var/tmp/GK_HOME
EXIT_CODE=$?

. /var/tmp/GK_HOME
rm /var/tmp/GK_HOME
if [ $EXIT_CODE -ne 0 ] ; then \
exit
fi

if [ $GK_HOME -eq 1 ] ; then \
sudo chmod -R a+rwx /var/tmp/GK_KNOPPIX
sudo chown -R knoppix.knoppix /var/tmp/GK_KNOPPIX

#sudo chmod a+rwx /var/tmp/GK_KNOPPIX/KNOPPIX/configs.tzb
#sudo chown -R knoppix.knoppix /var/tmp/GK_KNOPPIX/KNOPPIX/configs.tzb

echo "cd /cdrom/HOME" >> /var/tmp/GK_KNOPPIX/KNOPPIX/knoppix.sh
echo -n "cp -R ./ /home/knoppix/" >> /var/tmp/GK_KNOPPIX/KNOPPIX/knoppix.sh
fi


fi
# NOT IMPORTANT?  can put strings in the disk header but are they useful  ????
# the following reads these strings from the new DVD
### data="`dd if=/dev/cdrom ibs=1024 skip=32 count=1 2>/dev/null`"
# use one string --  no spaces  VERSION 16 characters,  P and  p up to 128 
#  hwclock | sed 's/ /_/g' | sed 's/............seconds/_|_/' > /var/tmp/GK_PUBLISHER2
# uname -snrv | sed 's/ /_/g' >> /var/tmp/GK_PUBLISHER2

Xdialog --title "GROW_KNOPPIX " --yesno "\
                          FINAL CHECK\n\n\
Clone directory  KNOPPIX  with the file  KNOPPIX  is at:\n\
-->$KNOPPIX_PATH\n\n\
Your burner is at:                ---or--- the iso path/name is:\n\
-->$DVD_DEV\n\n\
Your burner speed ( 0 = default)  ---or--- burn    iso    selected:\n\
-->$BURN_SPEED\n\n\
You are bringing together content from:\n\
-->$DVD_ROOT\n\n\
Your boot type is:\n\
-->$BOOT_VERSION\n\n\
To dry-run test or to burn -- you must have a blank DVD in the drive.\n\n\
           YES to do a dry-run.              NO to skip the dry-run.\
" 35 85
EXIT_CODE=$?

if [ $EXIT_CODE -ne 1 ] ; then \

#######REPEATED CODE
mkdir /var/tmp/BindCD
mkdir /var/tmp/BindCD/KNOPPIX
sudo chmod -R a+rwx /var/tmp/BindCD
sudo chown -R knoppix.knoppix /var/tmp/BindCD
echo -n "/home/knoppix/GROW_KNOPPIX/KNOPPIX/boot.img 100002\n" >/var/tmp/GK_SORT
echo -n "/home/knoppix/GROW_KNOPPIX/KNOPPIX/KNOPPIX 100001" >>/var/tmp/GK_SORT

echo -n "sudo mount --bind " > /var/tmp/GK_BURN
echo -n $KNOPPIX_PATH >> /var/tmp/GK_BURN
echo -n "/KNOPPIX/ /var/tmp/BindCD/KNOPPIX ;" >> /var/tmp/GK_BURN
echo -n "growisofs " >> /var/tmp/GK_BURN
echo -n "-dry-run " >> /var/tmp/GK_BURN
echo -n "-dvd-compat " >> /var/tmp/GK_BURN
if [ $BURN_SPEED != "0" ]; then
    echo -n "-speed=$BURN_SPEED " >> /var/tmp/GK_BURN
fi
echo -n "-Z $DVD_DEV " >> /var/tmp/GK_BURN
echo -n "-pad -l -r -J -v -sort /var/tmp/GK_SORT " >> /var/tmp/GK_BURN
echo -n "-V 'grow_knoppix1234' -P 'PUBLISHER1' -p 'PUBLISHER2' " >> /var/tmp/GK_BURN
echo -n "-A 'grow-knoppix.berlios.de' ">> /var/tmp/GK_BURN
if [ $BOOT_VERSION = "boot.img" ] ; then 
    echo -n "-b boot.img -c boot.cat " >> /var/tmp/GK_BURN
elif [ $BOOT_VERSION = "stage1_5" ] ; then
    echo -n "-no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/grub/iso9660_stage1_5 -c boot/grub/boot.cat " >>/var/tmp/GK_BURN
else
    echo -n "-no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat " >>/var/tmp/GK_BURN
fi
echo -n "-hide-rr-moved " >> /var/tmp/GK_BURN
echo -n $DVD_ROOT  >> /var/tmp/GK_BURN

echo -n "; rm /var/tmp/GK_SORT" >> /var/tmp/GK_BURN
echo -n "; echo "dry-run OK if is says - - - Writing:  - - -  CLICK X TO PROCEED" " >> /var/tmp/GK_BURN
#echo -n "; echo "CONGRATUALTIONS. -----> CLICK X to EXIT" " >> /var/tmp/GK_BURN
sudo chmod a+x /var/tmp/GK_BURN
xterm -hold -T "GROW-KNOPPIX" -bg black -fg green -cr red -ls -e /var/tmp/GK_BURN
 sudo umount /var/tmp/BindCD/KNOPPIX
 rm -R -f /var/tmp/BindCD
 rm /var/tmp/GK_BURN
#####END REPEATED CODE 
fi

echo -n "PUBLISHER=\"" > /var/tmp/GK_PUBLISHER

Xdialog --title "GROW_KNOPPIX " --inputbox "\
When the test has finished look at the results.\n\
If it says:       Writing:         then the test was good.\n\
Close the results box.  Then you may click YES to burn the DVD.\n\n\
Here are your settings:\n\n\
Your directory  KNOPPIX  with the file  KNOPPIX  is at -->\n\
$KNOPPIX_PATH\n\
Your burner is at -->\n\
$DVD_DEV\n\
You are bringing together content from -->\n\
$DVD_ROOT\n\n\n\n\n\
             Click  OK  to                     Click   Cancel  to\n\
             BURN NOW!                        exit.\n\n\n\n\n\
Optional identification up to 128 char. Do not use special characters.\n\
This notice may identify the publisher and his rights to added content\n\
It will be placed in the DVD header.\n\
" 35 85 $PUBLISHER 2>> /var/tmp/GK_PUBLISHER
EXIT_CODE=$?
echo -n "\"" >> /var/tmp/GK_PUBLISHER
. /var/tmp/GK_PUBLISHER
PUBLISHER=${DVD_DEV%?}
rm /var/tmp/GK_PUBLISHER

if [ $EXIT_CODE -ne 0 ] ; then
exit
fi

#####REPEATED EXCEPT -dry-run
#######REPEATED CODE
mkdir /var/tmp/BindCD
mkdir /var/tmp/BindCD/KNOPPIX
sudo chmod -R a+rwx /var/tmp/BindCD
sudo chown -R knoppix.knoppix /var/tmp/BindCD
echo -n "/home/knoppix/GROW_KNOPPIX/KNOPPIX/boot.img 100002\n" >/var/tmp/GK_SORT
echo -n "/home/knoppix/GROW_KNOPPIX/KNOPPIX/KNOPPIX 100001" >>/var/tmp/GK_SORT

echo -n "sudo mount --bind " > /var/tmp/GK_BURN
echo -n $KNOPPIX_PATH >> /var/tmp/GK_BURN
echo -n "/KNOPPIX/ /var/tmp/BindCD/KNOPPIX ;" >> /var/tmp/GK_BURN
echo -n "growisofs " >> /var/tmp/GK_BURN
#echo -n "-dry-run " >> /var/tmp/GK_BURN
echo -n "-dvd-compat " >> /var/tmp/GK_BURN
if [ $BURN_SPEED != "0" ]; then
    echo -n "-speed=$BURN_SPEED " >> /var/tmp/GK_BURN
fi
echo -n "-Z $DVD_DEV " >> /var/tmp/GK_BURN
echo -n " -pad -l -r -J -v -sort /var/tmp/GK_SORT " >> /var/tmp/GK_BURN
echo -n "-V 'grow_knoppix1234' -P 'PUBLISHER1' -p 'PUBLISHER2' " >> /var/tmp/GK_BURN
echo -n "-A 'grow-knoppix.berlios.de' ">> /var/tmp/GK_BURN
if [ $BOOT_VERSION = "boot.img" ] ; then 
    echo -n "-b boot.img -c boot.cat " >> /var/tmp/GK_BURN
elif [ $BOOT_VERSION = "stage1_5" ] ; then
    echo -n "-no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/grub/iso9660_stage1_5 -c boot/grub/boot.cat " >>/var/tmp/GK_BURN
else
    echo -n "-no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat " >>/var/tmp/GK_BURN
fi
echo -n "-hide-rr-moved " >> /var/tmp/GK_BURN
echo -n $DVD_ROOT  >> /var/tmp/GK_BURN

echo -n "; rm /var/tmp/GK_SORT" >> /var/tmp/GK_BURN
#echo -n "; echo "dry-run OK if is says - - - Writing:  - - -  CLICK X TO PROCEED" " >> /var/tmp/GK_BURN
echo -n "; echo "CONGRATUALTIONS. -----> CLICK X to EXIT" " >> /var/tmp/GK_BURN
sudo chmod a+x /var/tmp/GK_BURN
xterm -hold -T "GROW-KNOPPIX" -bg black -fg green -cr red -ls -e /var/tmp/GK_BURN
 sudo umount /var/tmp/BindCD/KNOPPIX
 rm -R -f /var/tmp/BindCD
 rm /var/tmp/GK_BURN
#####END REPEATED CODE

echo -n "; echo "CONGRATUALTIONS. -----> CLICK X to EXIT" " >> /var/tmp/GK_BURN
######END REPEAT
### Xdialog --title "DVD BURN LOG " --logbox /var/tmp/GK_BURN 35 85
